// Aura
// Reference file
// 
// This file has been auto-generated, for the strings to be picked up by the
// localization tool. The code is not necessarily valid and doesn't serve
// any other purpose.
//---------------------------------------------------------------------------

Localization.GetParticular("skillName", "Tailoring");
Localization.GetParticular("skillName", "Read in Detail");
Localization.GetParticular("skillName", "Rest");
Localization.GetParticular("skillName", "Town Cry");
Localization.GetParticular("skillName", "Campfire");
Localization.GetParticular("skillName", "First Aid");
Localization.GetParticular("skillName", "Gathering");
Localization.GetParticular("skillName", "Weaving");
Localization.GetParticular("skillName", "Milling");
Localization.GetParticular("skillName", "Handicraft");
Localization.GetParticular("skillName", "Refining");
Localization.GetParticular("skillName", "Blacksmithing");
Localization.GetParticular("skillName", "Cooking");
Localization.GetParticular("skillName", "Herbalism");
Localization.GetParticular("skillName", "Potion Making");
Localization.GetParticular("skillName", "Fishing");
Localization.GetParticular("skillName", "Production Mastery");
Localization.GetParticular("skillName", "Open Treasure Chest");
Localization.GetParticular("skillName", "Taming Wild Animals");
Localization.GetParticular("skillName", "Control Paddle");
Localization.GetParticular("skillName", "Metallurgy");
Localization.GetParticular("skillName", "Hot-Air Balloon Control");
Localization.GetParticular("skillName", "Carpentry");
Localization.GetParticular("skillName", "Make Theatre Mission Pass");
Localization.GetParticular("skillName", "Wine Making");
Localization.GetParticular("skillName", "Hillwen Engineering");
Localization.GetParticular("skillName", "Magic Craft");
Localization.GetParticular("skillName", "Rare Mineralogy");
Localization.GetParticular("skillName", "Shyllien Ecology");
Localization.GetParticular("skillName", "Tasting");
Localization.GetParticular("skillName", "Ingredient Hunting");
Localization.GetParticular("skillName", "Catering");
Localization.GetParticular("skillName", "Web Spinning");
Localization.GetParticular("skillName", "Wyvern Fire Breath");
Localization.GetParticular("skillName", "Save Location");
Localization.GetParticular("skillName", "Pet Teleport");
Localization.GetParticular("skillName", "PetJumpOnRiding");
Localization.GetParticular("skillName", "Sheep Shearing");
Localization.GetParticular("skillName", "Mining");
Localization.GetParticular("skillName", "Egg Gathering");
Localization.GetParticular("skillName", "Mushroom Gathering");
Localization.GetParticular("skillName", "Milking");
Localization.GetParticular("skillName", "Harvesting");
Localization.GetParticular("skillName", "Hoeing");
Localization.GetParticular("skillName", "Commerce Mastery");
Localization.GetParticular("skillName", "Transformation Mastery");
Localization.GetParticular("skillName", "Exploration Mastery");
Localization.GetParticular("skillName", "Artifact Investigation");
Localization.GetParticular("skillName", "Treasure Dungeon Exploration");
Localization.GetParticular("skillName", "Defense");
Localization.GetParticular("skillName", "Smash");
Localization.GetParticular("skillName", "Counterattack");
Localization.GetParticular("skillName", "Natural Shield");
Localization.GetParticular("skillName", "Heavy Stander");
Localization.GetParticular("skillName", "Mana Deflector");
Localization.GetParticular("skillName", "Full Swing");
Localization.GetParticular("skillName", "Final Smash");
Localization.GetParticular("skillName", "Fury of Bard");
Localization.GetParticular("skillName", "Jump");
Localization.GetParticular("skillName", "Charge");
Localization.GetParticular("skillName", "Assault Slash");
Localization.GetParticular("skillName", "Berserker");
Localization.GetParticular("skillName", "Berserker(hidden)");
Localization.GetParticular("skillName", "Lance Counter");
Localization.GetParticular("skillName", "Lance Charge");
Localization.GetParticular("skillName", "Rage Impact");
Localization.GetParticular("skillName", "Bash");
Localization.GetParticular("skillName", "Ranged Attack");
Localization.GetParticular("skillName", "Magnum Shot");
Localization.GetParticular("skillName", "Arrow Revolver");
Localization.GetParticular("skillName", "Arrow Revolver");
Localization.GetParticular("skillName", "Chaingun");
Localization.GetParticular("skillName", "Support Shot");
Localization.GetParticular("skillName", "Mirage Missile");
Localization.GetParticular("skillName", "Bomb Ignition");
Localization.GetParticular("skillName", "Spirit Bow Awakening");
Localization.GetParticular("skillName", "Throwing Attack");
Localization.GetParticular("skillName", "Hot-Air Balloon Crossbow Shot");
Localization.GetParticular("skillName", "Hot-Air Balloon Crossbow Shot (mini game)");
Localization.GetParticular("skillName", "Urgent Shot");
Localization.GetParticular("skillName", "Windmill");
Localization.GetParticular("skillName", "Stomp");
Localization.GetParticular("skillName", "Self Destruction Active");
Localization.GetParticular("skillName", "Final Hit");
Localization.GetParticular("skillName", "Spirit Sword Awakening");
Localization.GetParticular("skillName", "Spirit BW Awakening");
Localization.GetParticular("skillName", "Stomp");
Localization.GetParticular("skillName", "Wendigo Stomp");
Localization.GetParticular("skillName", "Alligator Full Swing");
Localization.GetParticular("skillName", "Giant Lion Roar");
Localization.GetParticular("skillName", "Crash Shot");
Localization.GetParticular("skillName", "Instinctive Reaction");
Localization.GetParticular("skillName", "Combat Mastery");
Localization.GetParticular("skillName", "Critical Hit");
Localization.GetParticular("skillName", "Natural Shield Passive");
Localization.GetParticular("skillName", "Heavy Stander Passive");
Localization.GetParticular("skillName", "Mana Deflector Passive");
Localization.GetParticular("skillName", "Dark Lord");
Localization.GetParticular("skillName", "Glas Ghaibhleann Skill");
Localization.GetParticular("skillName", "Self Destruction");
Localization.GetParticular("skillName", "Sharp Mind");
Localization.GetParticular("skillName", "Sword Mastery");
Localization.GetParticular("skillName", "Axe Mastery");
Localization.GetParticular("skillName", "Blunt Mastery");
Localization.GetParticular("skillName", "Shield Mastery");
Localization.GetParticular("skillName", "Heavy Armor Mastery");
Localization.GetParticular("skillName", "Light Armor Mastery");
Localization.GetParticular("skillName", "Dragon Tail Attack");
Localization.GetParticular("skillName", "Petrifying Roar");
Localization.GetParticular("skillName", "Fire Breath");
Localization.GetParticular("skillName", "Dash");
Localization.GetParticular("skillName", "Sandworm Melee Attack");
Localization.GetParticular("skillName", "Bite");
Localization.GetParticular("skillName", "Smack");
Localization.GetParticular("skillName", "Wind Guard");
Localization.GetParticular("skillName", "Taunt");
Localization.GetParticular("skillName", "Final Shot");
Localization.GetParticular("skillName", "Shadow Breath");
Localization.GetParticular("skillName", "Dark Flame");
Localization.GetParticular("skillName", "Light of Sword");
Localization.GetParticular("skillName", "Claimh Solas Dash");
Localization.GetParticular("skillName", "Claimh Solas Full Swing");
Localization.GetParticular("skillName", "Scarecrow Curse");
Localization.GetParticular("skillName", "Roar");
Localization.GetParticular("skillName", "Wall Decoration Fire Bolt");
Localization.GetParticular("skillName", "Wall Decoration Ice Bolt");
Localization.GetParticular("skillName", "Wall Decoration Lightning Bolt");
Localization.GetParticular("skillName", "Wall Decoration Bolt Attack");
Localization.GetParticular("skillName", "Wall Decoration Poison Gas Attack");
Localization.GetParticular("skillName", "Evasion");
Localization.GetParticular("skillName", "Python Stone Short Range Attack");
Localization.GetParticular("skillName", "Python Stone Breath");
Localization.GetParticular("skillName", "Nuadha Smash");
Localization.GetParticular("skillName", "Nuadha Light of Sword");
Localization.GetParticular("skillName", "Nuadha Smash");
Localization.GetParticular("skillName", "Roar");
Localization.GetParticular("skillName", "Grim Reaper Vertical Attack");
Localization.GetParticular("skillName", "Grim Reaper Horizontal Attack");
Localization.GetParticular("skillName", "Grim Reaper Windmill");
Localization.GetParticular("skillName", "Roar");
Localization.GetParticular("skillName", "Bow Mastery");
Localization.GetParticular("skillName", "Crossbow Mastery");
Localization.GetParticular("skillName", "Lance Mastery");
Localization.GetParticular("skillName", "Dual Wield Mastery");
Localization.GetParticular("skillName", "Bran's Shockwave");
Localization.GetParticular("skillName", "Bran's Arm Swing");
Localization.GetParticular("skillName", "Gold Strike");
Localization.GetParticular("skillName", "Charge");
Localization.GetParticular("skillName", "Playing Dead");
Localization.GetParticular("skillName", "Dragon Meteor");
Localization.GetParticular("skillName", "Red Dragon Fire Breath");
Localization.GetParticular("skillName", "Thunder Rain");
Localization.GetParticular("skillName", "Dragon Roar");
Localization.GetParticular("skillName", "Wyvern Lightning");
Localization.GetParticular("skillName", "Wyvern Ice Breath");
Localization.GetParticular("skillName", "Dragon Support Meteor");
Localization.GetParticular("skillName", "Bewilder");
Localization.GetParticular("skillName", "Neid Roar");
Localization.GetParticular("skillName", "Tail Whip");
Localization.GetParticular("skillName", "Water Bomb");
Localization.GetParticular("skillName", "Beholder Beam Attack");
Localization.GetParticular("skillName", "Axe Throwing");
Localization.GetParticular("skillName", "Chandelier Attack");
Localization.GetParticular("skillName", "Summon");
Localization.GetParticular("skillName", "Boost");
Localization.GetParticular("skillName", "Running Boost");
Localization.GetParticular("skillName", "Hop Spin");
Localization.GetParticular("skillName", "Multi Neagh Water Bomb");
Localization.GetParticular("skillName", "Wyvern Ice Breath (mini game)");
Localization.GetParticular("skillName", "SummonTester");
Localization.GetParticular("skillName", "WhiteDragonFear");
Localization.GetParticular("skillName", "BlackDragonFear");
Localization.GetParticular("skillName", "MadnessPilgrimage");
Localization.GetParticular("skillName", "HolyPilgrimage");
Localization.GetParticular("skillName", "WhiteDragonBreath");
Localization.GetParticular("skillName", "BlackDragonBreath");
Localization.GetParticular("skillName", "StampFromHell");
Localization.GetParticular("skillName", "DevilHug");
Localization.GetParticular("skillName", "TightDefenseBlow");
Localization.GetParticular("skillName", "CastleDefenseBlow");
Localization.GetParticular("skillName", "Merrow Smash");
Localization.GetParticular("skillName", "Abyss Snare");
Localization.GetParticular("skillName", "Abyss Judgment");
Localization.GetParticular("skillName", "Abyss Terror");
Localization.GetParticular("skillName", "Duke's Kiss");
Localization.GetParticular("skillName", "Duke's Rose");
Localization.GetParticular("skillName", "Duke's Mist");
Localization.GetParticular("skillName", "Duke's Temptation");
Localization.GetParticular("skillName", "Spooky Sounds");
Localization.GetParticular("skillName", "Titan Kick");
Localization.GetParticular("skillName", "Titan Bump");
Localization.GetParticular("skillName", "Titan Leap");
Localization.GetParticular("skillName", "Vertical Spin Attack");
Localization.GetParticular("skillName", "Horizontal Spin Attack");
Localization.GetParticular("skillName", "Dian Stab");
Localization.GetParticular("skillName", "Dian Stomp");
Localization.GetParticular("skillName", "Dian Trap");
Localization.GetParticular("skillName", "Dragon Ruairi Swing");
Localization.GetParticular("skillName", "Dragon Ruairi Grab");
Localization.GetParticular("skillName", "Dragon Ruairi Rush");
Localization.GetParticular("skillName", "Staff Swing");
Localization.GetParticular("skillName", "Holy Contagion");
Localization.GetParticular("skillName", "Holy Confinement");
Localization.GetParticular("skillName", "Fanaticism");
Localization.GetParticular("skillName", "Soul Absorption");
Localization.GetParticular("skillName", "Mineral Hail");
Localization.GetParticular("skillName", "Alban Ambush Attack");
Localization.GetParticular("skillName", "Alban Ice Spray");
Localization.GetParticular("skillName", "Alban Arrow Rain");
Localization.GetParticular("skillName", "Necromancy");
Localization.GetParticular("skillName", "Phantom's Roar");
Localization.GetParticular("skillName", "Solidify");
Localization.GetParticular("skillName", "Freeze! Stop Right There!");
Localization.GetParticular("skillName", "Crisis Escape");
Localization.GetParticular("skillName", "Excalibur");
Localization.GetParticular("skillName", "Invisible Air");
Localization.GetParticular("skillName", "Unlimited Blade Works");
Localization.GetParticular("skillName", "The Fake Spiral Sword");
Localization.GetParticular("skillName", "Enuma Elish");
Localization.GetParticular("skillName", "King's Treasure");
Localization.GetParticular("skillName", "God Hand: Twelve Labors");
Localization.GetParticular("skillName", "Spinning Slash");
Localization.GetParticular("skillName", "Super Windmill (GM Skill)");
Localization.GetParticular("skillName", "Kill All");
Localization.GetParticular("skillName", "Kill Self");
Localization.GetParticular("skillName", "Administrative Picking2");
Localization.GetParticular("skillName", "Chain Casting");
Localization.GetParticular("skillName", "Bran's Charge");
Localization.GetParticular("skillName", "Meditation");
Localization.GetParticular("skillName", "Enchant");
Localization.GetParticular("skillName", "Healing");
Localization.GetParticular("skillName", "Magic Mastery");
Localization.GetParticular("skillName", "Party Healing");
Localization.GetParticular("skillName", "Meditaion for Pets");
Localization.GetParticular("skillName", "Life Drain");
Localization.GetParticular("skillName", "Mirror Witch Rest");
Localization.GetParticular("skillName", "Monster Resurrection");
Localization.GetParticular("skillName", "Yarn Binding!");
Localization.GetParticular("skillName", "Silent Move");
Localization.GetParticular("skillName", "Fire Mastery");
Localization.GetParticular("skillName", "Ice Mastery");
Localization.GetParticular("skillName", "Lightning Mastery");
Localization.GetParticular("skillName", "Bolt Mastery");
Localization.GetParticular("skillName", "Magic Wand Mastery");
Localization.GetParticular("skillName", "Magic Staff Mastery");
Localization.GetParticular("skillName", "Magic Weapon Mastery");
Localization.GetParticular("skillName", "Lightning Bolt");
Localization.GetParticular("skillName", "Thunder");
Localization.GetParticular("skillName", "Floating Stone Thunder");
Localization.GetParticular("skillName", "Thunder");
Localization.GetParticular("skillName", "Lightning Rod");
Localization.GetParticular("skillName", "Firebolt");
Localization.GetParticular("skillName", "Fireball");
Localization.GetParticular("skillName", "Training Fireball");
Localization.GetParticular("skillName", "Floating Stone Fire Ball");
Localization.GetParticular("skillName", "Meteor Strike");
Localization.GetParticular("skillName", "Icebolt");
Localization.GetParticular("skillName", "Ice Spear");
Localization.GetParticular("skillName", "icehug");
Localization.GetParticular("skillName", "Super Ice Bolt (GM Skill)");
Localization.GetParticular("skillName", "Water Spray");
Localization.GetParticular("skillName", "Floating Stone Ice Spear");
Localization.GetParticular("skillName", "Hail Storm");
Localization.GetParticular("skillName", "Spirit Wand Awakening");
Localization.GetParticular("skillName", "Assault Slash");
Localization.GetParticular("skillName", "Berserker");
Localization.GetParticular("skillName", "Fire Lightning");
Localization.GetParticular("skillName", "Fusion Bolt");
Localization.GetParticular("skillName", "Fire Shield");
Localization.GetParticular("skillName", "Ice Shield");
Localization.GetParticular("skillName", "Lightning Shield");
Localization.GetParticular("skillName", "Natural Shield");
Localization.GetParticular("skillName", "Mana Shield");
Localization.GetParticular("skillName", "Blaze");
Localization.GetParticular("skillName", "Paper Airplane Bomb");
Localization.GetParticular("skillName", "Invitation of Death");
Localization.GetParticular("skillName", "Flames of Hell");
Localization.GetParticular("skillName", "Spellwalk");
Localization.GetParticular("skillName", "Snap Cast");
Localization.GetParticular("skillName", "Inspiration");
Localization.GetParticular("skillName", "Swallow");
Localization.GetParticular("skillName", "Bubble Blast");
Localization.GetParticular("skillName", "Master Teleport");
Localization.GetParticular("skillName", "Detection");
Localization.GetParticular("skillName", "Hide");
Localization.GetParticular("skillName", "Shadow Death");
Localization.GetParticular("skillName", "Thunder Storm");
Localization.GetParticular("skillName", "Thunder Breath");
Localization.GetParticular("skillName", "Fire Storm");
Localization.GetParticular("skillName", "Fire Breath");
Localization.GetParticular("skillName", "Ice Storm");
Localization.GetParticular("skillName", "Flame Dive");
Localization.GetParticular("skillName", "Hands of Salvation");
Localization.GetParticular("skillName", "Frost Storm");
Localization.GetParticular("skillName", "Ice Breath");
Localization.GetParticular("skillName", "Flame of Resurrection");
Localization.GetParticular("skillName", "Explosive Resurrection");
Localization.GetParticular("skillName", "Phoenix's Flame");
Localization.GetParticular("skillName", "Devil's Dash");
Localization.GetParticular("skillName", "Petrifying Roar");
Localization.GetParticular("skillName", "Devil's Cry");
Localization.GetParticular("skillName", "Restful Wind");
Localization.GetParticular("skillName", "Holy Shower");
Localization.GetParticular("skillName", "Holy Rush");
Localization.GetParticular("skillName", "Burnout");
Localization.GetParticular("skillName", "Hop In");
Localization.GetParticular("skillName", "Hop Shield");
Localization.GetParticular("skillName", "Truck to the Head");
Localization.GetParticular("skillName", "Sleepy Dust");
Localization.GetParticular("skillName", "Cleansing Dust");
Localization.GetParticular("skillName", "Healing Breeze");
Localization.GetParticular("skillName", "Wool of the Gods");
Localization.GetParticular("skillName", "Song of Tuan");
Localization.GetParticular("skillName", "Whisper of Tuan");
Localization.GetParticular("skillName", "Grudge of Tuan");
Localization.GetParticular("skillName", "Curse of Devil");
Localization.GetParticular("skillName", "Cold Winter Performance");
Localization.GetParticular("skillName", "Requiem");
Localization.GetParticular("skillName", "Oil Squirt");
Localization.GetParticular("skillName", "Tiny Jibes");
Localization.GetParticular("skillName", "Farewell Surprise");
Localization.GetParticular("skillName", "Lightning Breath");
Localization.GetParticular("skillName", "Dragon Rage");
Localization.GetParticular("skillName", "Yui's Defense");
Localization.GetParticular("skillName", "Merrow Rising Dragon");
Localization.GetParticular("skillName", "Merrow Tidal Wave");
Localization.GetParticular("skillName", "Titan Regeneration");
Localization.GetParticular("skillName", "Halo of Torment");
Localization.GetParticular("skillName", "Butterfly Kiss");
Localization.GetParticular("skillName", "Pyrosphere");
Localization.GetParticular("skillName", "Soul Rift");
Localization.GetParticular("skillName", "Queen's Meteor");
Localization.GetParticular("skillName", "Fragmentation");
Localization.GetParticular("skillName", "Synthesis");
Localization.GetParticular("skillName", "Mana Crystallization");
Localization.GetParticular("skillName", "Life Drain");
Localization.GetParticular("skillName", "Alchemy Mastery");
Localization.GetParticular("skillName", "Water Cannon");
Localization.GetParticular("skillName", "Crystallization");
Localization.GetParticular("skillName", "Barrier Spikes");
Localization.GetParticular("skillName", "Wind Blast");
Localization.GetParticular("skillName", "Flame Burst");
Localization.GetParticular("skillName", "Sand Burst");
Localization.GetParticular("skillName", "Rain Casting");
Localization.GetParticular("skillName", "Frozen Blast");
Localization.GetParticular("skillName", "Metal Conversion");
Localization.GetParticular("skillName", "Shock");
Localization.GetParticular("skillName", "Heat Buster");
Localization.GetParticular("skillName", "Chain Cylinder");
Localization.GetParticular("skillName", "Fire Alchemy");
Localization.GetParticular("skillName", "Water Alchemy");
Localization.GetParticular("skillName", "Clay Alchemy");
Localization.GetParticular("skillName", "Wind Alchemy");
Localization.GetParticular("skillName", "AlchemyCylinderMastery");
Localization.GetParticular("skillName", "Transmutation");
Localization.GetParticular("skillName", "Elemental Wave");
Localization.GetParticular("skillName", "Golden Time");
Localization.GetParticular("skillName", "Hydra Transmutation");
Localization.GetParticular("skillName", "Guard Cylinder Mastery");
Localization.GetParticular("skillName", "Spirit Cylinder Awakening");
Localization.GetParticular("skillName", "Summon Golem");
Localization.GetParticular("skillName", "Mana Crystallization Counter-Transmutation");
Localization.GetParticular("skillName", "Knuckle Mastery");
Localization.GetParticular("skillName", "Chain Mastery");
Localization.GetParticular("skillName", "Charging Strike");
Localization.GetParticular("skillName", "Focused Fist");
Localization.GetParticular("skillName", "Spinning Uppercut");
Localization.GetParticular("skillName", "Somersault Kick");
Localization.GetParticular("skillName", "Drop Kick");
Localization.GetParticular("skillName", "Pummel");
Localization.GetParticular("skillName", "Respite");
Localization.GetParticular("skillName", "Tumble");
Localization.GetParticular("skillName", "Playing Instrument");
Localization.GetParticular("skillName", "Composing");
Localization.GetParticular("skillName", "Musical Knowledge");
Localization.GetParticular("skillName", "Enthralling Performance");
Localization.GetParticular("skillName", "Dischord");
Localization.GetParticular("skillName", "Encore");
Localization.GetParticular("skillName", "Fantastic Chorus");
Localization.GetParticular("skillName", "Battlefield Overture");
Localization.GetParticular("skillName", "Lullaby");
Localization.GetParticular("skillName", "Vivace");
Localization.GetParticular("skillName", "Enduring Melody");
Localization.GetParticular("skillName", "Harvest Song");
Localization.GetParticular("skillName", "March Song");
Localization.GetParticular("skillName", "Song");
Localization.GetParticular("skillName", "Control Marionette");
Localization.GetParticular("skillName", "Pierrot Marionette");
Localization.GetParticular("skillName", "Colossus Marionette");
Localization.GetParticular("skillName", "Act 2: Threshold Cutter");
Localization.GetParticular("skillName", "Act 1: Inciting Incident");
Localization.GetParticular("skillName", "Act 4: Rising Action");
Localization.GetParticular("skillName", "Act 6: Crisis");
Localization.GetParticular("skillName", "Act 7: Climactic Crash");
Localization.GetParticular("skillName", "Act 9: Invigorating Encore");
Localization.GetParticular("skillName", "Act 2: Threshold Cutter AI");
Localization.GetParticular("skillName", "Act 1: Inciting Incident AI");
Localization.GetParticular("skillName", "Act 4: Rising Action AI");
Localization.GetParticular("skillName", "Act 6: Crisis AI");
Localization.GetParticular("skillName", "Act 7: Climactic Crash AI");
Localization.GetParticular("skillName", "Act 9: Invigorating Encore AI");
Localization.GetParticular("skillName", "Wire Pull");
Localization.GetParticular("skillName", "Puppet's Snare");
Localization.GetParticular("skillName", "Dual Gun Mastery");
Localization.GetParticular("skillName", "Flash Launcher");
Localization.GetParticular("skillName", "Grapple Shot");
Localization.GetParticular("skillName", "Bullet Slide");
Localization.GetParticular("skillName", "Shooting Rush");
Localization.GetParticular("skillName", "Bullet Storm");
Localization.GetParticular("skillName", "Reload");
Localization.GetParticular("skillName", "Way of the Gun");
Localization.GetParticular("skillName", "Shuriken Mastery");
Localization.GetParticular("skillName", "Shuriken Charge");
Localization.GetParticular("skillName", "Kunai Storm");
Localization.GetParticular("skillName", "Shadow Bind");
Localization.GetParticular("skillName", "Shadow Cloak");
Localization.GetParticular("skillName", "Explosive Kunai");
Localization.GetParticular("skillName", "Smokescreen");
Localization.GetParticular("skillName", "Sakura Abyss");
Localization.GetParticular("skillName", "Spirit of Order");
Localization.GetParticular("skillName", "Power of Order");
Localization.GetParticular("skillName", "Eye of Order");
Localization.GetParticular("skillName", "Sword of Order");
Localization.GetParticular("skillName", "Pal. Natural Shield");
Localization.GetParticular("skillName", "Pal. Heavy Stander");
Localization.GetParticular("skillName", "Pal. Mana Deflector");
Localization.GetParticular("skillName", "Soul of Chaos");
Localization.GetParticular("skillName", "Control of Darkness");
Localization.GetParticular("skillName", "Body of Chaos");
Localization.GetParticular("skillName", "Mind of Chaos");
Localization.GetParticular("skillName", "Hands of Chaos");
Localization.GetParticular("skillName", "Dark Natural Shield");
Localization.GetParticular("skillName", "Dark Heavy Stander");
Localization.GetParticular("skillName", "Dark Mana Deflector");
Localization.GetParticular("skillName", "Race Transformation");
Localization.GetParticular("skillName", "WindMill");
Localization.GetParticular("skillName", "Fury of Connous");
Localization.GetParticular("skillName", "Elven Magic Missile");
Localization.GetParticular("skillName", "Armor of Connous");
Localization.GetParticular("skillName", "Mind of Connous");
Localization.GetParticular("skillName", "Sharpness of Con.");
Localization.GetParticular("skillName", "Natural Shield");
Localization.GetParticular("skillName", "Heavy Stander");
Localization.GetParticular("skillName", "Mana Deflector");
Localization.GetParticular("skillName", "Daemon of Physis");
Localization.GetParticular("skillName", "Giant Full Swing");
Localization.GetParticular("skillName", "Shield of Physis");
Localization.GetParticular("skillName", "Life of Physis");
Localization.GetParticular("skillName", "Spell of Physis");
Localization.GetParticular("skillName", "Natural Shield");
Localization.GetParticular("skillName", "Heavy Stander");
Localization.GetParticular("skillName", "Mana Deflector");
Localization.GetParticular("skillName", "Nuadha Spear of Light");
Localization.GetParticular("skillName", "Nuadha Fury of Light");
Localization.GetParticular("skillName", "Awakening of Light");
Localization.GetParticular("skillName", "Spear of Light");
Localization.GetParticular("skillName", "Fury of Light");
Localization.GetParticular("skillName", "Awakening of Light");
Localization.GetParticular("skillName", "Spear of Light");
Localization.GetParticular("skillName", "Fury of Light");
Localization.GetParticular("skillName", "Shadow Spirit");
Localization.GetParticular("skillName", "Wings of Eclipse");
Localization.GetParticular("skillName", "Wings of Rage");
Localization.GetParticular("skillName", "Shield of Trust");
Localization.GetParticular("skillName", "Celestial Spike");
Localization.GetParticular("skillName", "Judgment Blade");
Localization.GetParticular("skillName", "Divine Link");
Localization.GetParticular("skillName", "Sketch");
Localization.GetParticular("skillName", "L-Rod Exploration");
Localization.GetParticular("skillName", "Play dead");
Localization.GetParticular("skillName", "Hide");
Localization.GetParticular("skillName", "Performance");
Localization.GetParticular("skillName", "Land Maker");
Localization.GetParticular("skillName", "Rock Throwing");
Localization.GetParticular("skillName", "Dice Tossing");
Localization.GetParticular("skillName", "Jam Session");
Localization.GetParticular("skillName", "Throw Paper Airplane");
Localization.GetParticular("skillName", "Water Balloon\nThrowing");
Localization.GetParticular("skillName", "Cylinder On/Off");
Localization.GetParticular("skillName", "Continent Warp");
Localization.GetParticular("skillName", "Add Seasoning");
Localization.GetParticular("skillName", "Chorus");
Localization.GetParticular("skillName", "Inflate Balloon");
Localization.GetParticular("skillName", "Group Gesture");
Localization.GetParticular("skillName", "Release Sky Lantern");
Localization.GetParticular("skillName", "Watering");
Localization.GetParticular("skillName", "Fertilizing");
Localization.GetParticular("skillName", "Bug Catching");
Localization.GetParticular("skillName", "Umbrella");
Localization.GetParticular("skillName", "Scare");
Localization.GetParticular("skillName", "Normal Attack");
Localization.GetParticular("skillName", "Spread Wings");
Localization.GetParticular("skillName", "Outfit Action");
Localization.GetParticular("skillName", "Couples Flight");
Localization.GetParticular("skillName", "Flight");
Localization.GetParticular("skillName", "Outfit Action 2");
Localization.GetParticular("skillName", "Sweethearts Flight");
Localization.GetParticular("skillName", "Yui Strike");
Localization.GetParticular("skillName", "Saber Strike");
Localization.GetParticular("skillName", "Archer Strike");
Localization.GetParticular("skillName", "Rin Strike");
Localization.GetParticular("skillName", "Illya Strike");
Localization.GetParticular("skillName", "Bolt Out of the Blue");
Localization.GetParticular("skillName", "Hamlet's Anguish");
Localization.GetParticular("skillName", "Claudius's Conspiracy");
Localization.GetParticular("skillName", "Ophelia's Tears");
Localization.GetParticular("skillName", "Romeo's Confession");
Localization.GetParticular("skillName", "Tybalt's Fencing Skills");
Localization.GetParticular("skillName", "Juliet's Feelings");
Localization.GetParticular("skillName", "Shylock's Step");
Localization.GetParticular("skillName", "Study: Potion Lore");
Localization.GetParticular("skillName", "Spider Shot");
Localization.GetParticular("skillName", "Doppelganger");
Localization.GetParticular("skillName", "Berserk");
Localization.GetParticular("skillName", "Chain: Counter Punch");
Localization.GetParticular("skillName", "Shockwave");
Localization.GetParticular("skillName", "Exclusive Street Artist skill");
Localization.GetParticular("skillName", "Gardening");
Localization.GetParticular("skillName", "Install Kiosk");
Localization.GetParticular("skillName", "Anger Management");
Localization.GetParticular("skillName", "Dagger Mastery");
Localization.GetParticular("skillName", "Dual Weapon Mastery");
Localization.GetParticular("skillName", "Python Stone Long Range Attack");
Localization.GetParticular("skillName", "Loot");
Localization.GetParticular("skillName", "Escape");
Localization.GetParticular("skillName", "Hidden Enchant");
Localization.GetParticular("skillName", "Hidden Resurrection");
Localization.GetParticular("skillName", "Hidden TownBack");
Localization.GetParticular("skillName", "Hidden Guild Stone Setting");
Localization.GetParticular("skillName", "Hidden Blessing");
Localization.GetParticular("skillName", "Campfire Kit");
Localization.GetParticular("skillName", "Skill Reset Kit");
Localization.GetParticular("skillName", "Big Blessing Water Kit");
Localization.GetParticular("skillName", "Dye");
Localization.GetParticular("skillName", "Elemental Enchant-All Slots");
Localization.GetParticular("skillName", "Hidden Poison Lathering Skill");
Localization.GetParticular("skillName", "Hide Bomb-Use Skill");
Localization.GetParticular("skillName", "MakeChocoStatue");
Localization.GetParticular("skillName", "Fossil Restoration");
Localization.GetParticular("skillName", "SeesawJump");
Localization.GetParticular("skillName", "SeesawCreate");
Localization.GetParticular("skillName", "Dragon Support");
Localization.GetParticular("skillName", "Ice Mine");
Localization.GetParticular("skillName", "Scan");
Localization.GetParticular("skillName", "Use support items");
Localization.GetParticular("skillName", "Ticking Quiz Bomb");
Localization.GetParticular("skillName", "Item Seal");
Localization.GetParticular("skillName", "Item Unseal");
Localization.GetParticular("skillName", "Use a Dungeon Pass");
Localization.GetParticular("skillName", "Use an Elatha Item");
Localization.GetParticular("skillName", "Throw Confetti");
Localization.GetParticular("skillName", "Use Party Popper");
Localization.GetParticular("skillName", "Feed Fish");
Localization.GetParticular("skillName", "Hammer Game");
Localization.GetParticular("skillName", "Spirit Shift");
Localization.GetParticular("skillName", "B+ Bomb");
Localization.GetParticular("skillName", "Name Color Change");
Localization.GetParticular("skillName", "Holy Flame");
Localization.GetParticular("skillName", "Use Morrighan's Feather");
Localization.GetParticular("skillName", "Create Falias Portal");
Localization.GetParticular("skillName", "UseItemChattingColorChange");
Localization.GetParticular("skillName", "Instal Private Farm Facility");
Localization.GetParticular("skillName", "Reorient Homestead building");
Localization.GetParticular("skillName", "Paint");
Localization.GetParticular("skillName", "Mix Paint");
Localization.GetParticular("skillName", "Water Balloon Attack");
Localization.GetParticular("skillName", "Emergency Ice Bomb");
Localization.GetParticular("skillName", "Marionette Hidden Resurrection");
Localization.GetParticular("skillName", "Touch Sand");
Localization.GetParticular("skillName", "Complete Hidden Resurrection Skill");
Localization.GetParticular("skillName", "Roll the dice 2");
Localization.GetParticular("skillName", "Release Sky Lantern (Hidden skills)");
Localization.GetParticular("skillName", "Pet Buffing");
Localization.GetParticular("skillName", "PetSealToItem");
Localization.GetParticular("skillName", "Eat Volcanic Bomb");
Localization.GetParticular("skillName", "CherryTreeKit");
Localization.GetParticular("skillName", "Spin");
Localization.GetParticular("skillName", "Rise and Dive");
Localization.GetParticular("skillName", "Beholder Alarm");
Localization.GetParticular("skillName", "GachaponSynthesis");
Localization.GetParticular("skillName", "Flown Hot-Air Balloon");
Localization.GetParticular("skillName", "Seal Item");
Localization.GetParticular("skillName", "Cure Zombie");
Localization.GetParticular("skillName", "GoldenHeartMeteor");
Localization.GetParticular("skillName", "GoldenHeartFear");
Localization.GetParticular("skillName", "Beast Roar");
Localization.GetParticular("skillName", "Dance Time");
Localization.GetParticular("skillName", "Cobweb");
Localization.GetParticular("skillName", "Holy Rampage");
Localization.GetParticular("skillName", "Book Shelving");
Localization.GetParticular("skillName", "Tail Chase Bomb");
Localization.GetParticular("skillName", "Pickup Item (GM Skill)");
Localization.GetParticular("skillName", "Block World (GM Skill)");
